# Generated by Django 5.1.1 on 2024-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute', models.CharField(default='USD-RUB', max_length=50)),
                ('value', models.IntegerField()),
                ('create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
